import { useCallback, useMemo, useState } from "react";
import { api } from "../../../api";
import type { Memory } from "../../../types";
import { formatRelative } from "../SettingsSection";
import { useAsyncResource } from "@/hooks/useAsyncResource";
import { CheckboxField } from "@/components/CheckboxField";
import { Panel } from "@/components/Panel";
import { RefreshButton } from "@/components/RefreshButton";
import { ErrorBanner } from "@/components/ErrorBanner";
import { EmptyState } from "@/components/EmptyState";

export function CuriositySeedsPanel() {
  const [running, setRunning] = useState(false);
  const [showConsumed, setShowConsumed] = useState(false);

  const loader = useCallback(
    async () =>
      ((
        await api.listMemories({
          kind: "curiosity_seed",
          limit: 50,
          order: "recent",
        })
      ).memories as Memory[]) || [],
    [],
  );
  const {
    data: seeds,
    loading,
    error,
    setError,
    refresh,
  } = useAsyncResource<Memory[]>(loader, []);

  const onRun = useCallback(async () => {
    setRunning(true);
    setError(null);
    try {
      await api.runCuriositySeedWorker();
      await refresh();
    } catch (err) {
      setError(String(err));
    } finally {
      setRunning(false);
    }
  }, [refresh, setError]);

  const visible = useMemo(() => {
    if (showConsumed) return seeds;
    return seeds.filter((seed) => {
      const meta = (seed.metadata || {}) as Record<string, unknown>;
      return !meta["consumed_at"];
    });
  }, [seeds, showConsumed]);

  const activeCount = useMemo(
    () =>
      seeds.filter((seed) => {
        const meta = (seed.metadata || {}) as Record<string, unknown>;
        return !meta["consumed_at"];
      }).length,
    [seeds],
  );

  return (
    <Panel>
      <div className="flex items-center justify-between gap-2 text-[11px]">
        <span
          className="font-medium text-ink-100/70"
          title="Topics Aiko has been quietly wondering about that haven't come up yet. Generated by the K9 curiosity seed worker during idle windows; consumed once the conversation drifts onto them."
        >
          Quiet curiosities
          <span className="ml-2 text-ink-100/40">({activeCount} active)</span>
        </span>
        <div className="flex items-center gap-2 text-ink-100/50">
          <CheckboxField
            className="gap-1"
            checked={showConsumed}
            onChange={setShowConsumed}
          >
            <span>show consumed</span>
          </CheckboxField>
          <RefreshButton
            onClick={onRun}
            loading={running || loading}
            label="regenerate now"
            title="Force one CuriositySeedWorker.run() now (instead of waiting for the next idle tick)."
          />
          <RefreshButton onClick={refresh} loading={loading} />
        </div>
      </div>
      {error ? <ErrorBanner compact>{error}</ErrorBanner> : null}
      {visible.length === 0 ? (
        <EmptyState>
          No active seeds. The worker runs once an hour during idle
          windows; click "regenerate now" to force one immediately.
        </EmptyState>
      ) : (
        <ul className="space-y-1">
          {visible.map((seed) => {
            const meta = (seed.metadata || {}) as Record<string, unknown>;
            const topic =
              (typeof meta["topic"] === "string" && meta["topic"]) ||
              seed.content ||
              "(unnamed)";
            const promptText =
              typeof meta["prompt_text"] === "string"
                ? (meta["prompt_text"] as string)
                : "";
            const consumedAt =
              typeof meta["consumed_at"] === "string"
                ? (meta["consumed_at"] as string)
                : null;
            const generatedAt =
              typeof meta["generated_at"] === "string"
                ? (meta["generated_at"] as string)
                : seed.created_at || null;
            const consumed = Boolean(consumedAt);
            return (
              <li
                key={seed.id}
                className={`rounded border px-2 py-1.5 text-[11px] ${
                  consumed
                    ? "border-emerald-400/30 bg-emerald-500/5 text-ink-100/60"
                    : "border-white/5 bg-white/[0.03]"
                }`}
              >
                <div className="flex items-center justify-between gap-2">
                  <span
                    className={`font-medium ${
                      consumed ? "line-through" : "text-ink-100/85"
                    }`}
                  >
                    {topic}
                  </span>
                  <span className="shrink-0 text-ink-100/40">
                    {formatRelative(generatedAt)}
                    {consumed ? (
                      <span className="ml-2 text-emerald-300/80">
                        consumed
                      </span>
                    ) : null}
                  </span>
                </div>
                {promptText ? (
                  <p
                    className={`mt-0.5 italic text-ink-100/55 ${
                      consumed ? "line-through" : ""
                    }`}
                  >
                    {promptText}
                  </p>
                ) : null}
              </li>
            );
          })}
        </ul>
      )}
    </Panel>
  );
}
