import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../../../api";
import type { Memory } from "../../../types";
import { formatRelative } from "../SettingsSection";

export function CuriositySeedsPanel() {
  const [seeds, setSeeds] = useState<Memory[]>([]);
  const [loading, setLoading] = useState(false);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showConsumed, setShowConsumed] = useState(false);

  const refresh = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await api.listMemories({
        kind: "curiosity_seed",
        limit: 50,
        order: "recent",
      });
      setSeeds((data.memories as Memory[]) || []);
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const onRun = useCallback(async () => {
    setRunning(true);
    setError(null);
    try {
      await api.runCuriositySeedWorker();
      await refresh();
    } catch (err) {
      setError(String(err));
    } finally {
      setRunning(false);
    }
  }, [refresh]);

  const visible = useMemo(() => {
    if (showConsumed) return seeds;
    return seeds.filter((seed) => {
      const meta = (seed.metadata || {}) as Record<string, unknown>;
      return !meta["consumed_at"];
    });
  }, [seeds, showConsumed]);

  const activeCount = useMemo(
    () =>
      seeds.filter((seed) => {
        const meta = (seed.metadata || {}) as Record<string, unknown>;
        return !meta["consumed_at"];
      }).length,
    [seeds],
  );

  return (
    <div className="mt-4 space-y-2 rounded-md border border-white/5 bg-white/[0.02] p-3">
      <div className="flex items-center justify-between gap-2 text-[11px]">
        <span
          className="font-medium text-ink-100/70"
          title="Topics Aiko has been quietly wondering about that haven't come up yet. Generated by the K9 curiosity seed worker during idle windows; consumed once the conversation drifts onto them."
        >
          Quiet curiosities
          <span className="ml-2 text-ink-100/40">({activeCount} active)</span>
        </span>
        <div className="flex items-center gap-2 text-ink-100/50">
          <label className="flex items-center gap-1">
            <input
              type="checkbox"
              checked={showConsumed}
              onChange={(e) => setShowConsumed(e.target.checked)}
            />
            <span>show consumed</span>
          </label>
          <button
            type="button"
            onClick={onRun}
            disabled={running || loading}
            className="rounded border border-white/10 px-2 py-0.5 hover:border-ink-400 disabled:opacity-40"
            title="Force one CuriositySeedWorker.run() now (instead of waiting for the next idle tick)."
          >
            {running ? "..." : "regenerate now"}
          </button>
          <button
            type="button"
            onClick={refresh}
            disabled={loading}
            className="rounded border border-white/10 px-2 py-0.5 hover:border-ink-400 disabled:opacity-40"
          >
            {loading ? "..." : "refresh"}
          </button>
        </div>
      </div>
      {error ? (
        <div className="rounded border border-rose-400/40 bg-rose-500/10 px-2 py-1 text-[11px] text-rose-200">
          {error}
        </div>
      ) : null}
      {visible.length === 0 ? (
        <p className="text-[11px] text-ink-100/40">
          No active seeds. The worker runs once an hour during idle
          windows; click "regenerate now" to force one immediately.
        </p>
      ) : (
        <ul className="space-y-1">
          {visible.map((seed) => {
            const meta = (seed.metadata || {}) as Record<string, unknown>;
            const topic =
              (typeof meta["topic"] === "string" && meta["topic"]) ||
              seed.content ||
              "(unnamed)";
            const promptText =
              typeof meta["prompt_text"] === "string"
                ? (meta["prompt_text"] as string)
                : "";
            const consumedAt =
              typeof meta["consumed_at"] === "string"
                ? (meta["consumed_at"] as string)
                : null;
            const generatedAt =
              typeof meta["generated_at"] === "string"
                ? (meta["generated_at"] as string)
                : seed.created_at || null;
            const consumed = Boolean(consumedAt);
            return (
              <li
                key={seed.id}
                className={`rounded border px-2 py-1.5 text-[11px] ${
                  consumed
                    ? "border-emerald-400/30 bg-emerald-500/5 text-ink-100/60"
                    : "border-white/5 bg-white/[0.03]"
                }`}
              >
                <div className="flex items-center justify-between gap-2">
                  <span
                    className={`font-medium ${
                      consumed ? "line-through" : "text-ink-100/85"
                    }`}
                  >
                    {topic}
                  </span>
                  <span className="shrink-0 text-ink-100/40">
                    {formatRelative(generatedAt)}
                    {consumed ? (
                      <span className="ml-2 text-emerald-300/80">
                        consumed
                      </span>
                    ) : null}
                  </span>
                </div>
                {promptText ? (
                  <p
                    className={`mt-0.5 italic text-ink-100/55 ${
                      consumed ? "line-through" : ""
                    }`}
                  >
                    {promptText}
                  </p>
                ) : null}
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
